"""
Customer Chat Interface: Outdoor Retail Recommender
Claude/ChatGPT-style conversational flow
Collects company info → calls Agent 3 (profiler) + Scout Agent → shows results
"""

import streamlit as st
import json
import sys
from pathlib import Path
from datetime import datetime

from dotenv import load_dotenv
import os
load_dotenv()

sys.path.insert(0, str(Path(__file__).parent.parent))

from Agents.decision_agent.pipeline import run_pipeline

st.set_page_config(
    page_title="Zenline | Retail Recommender",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# ============================================================================
# INITIALIZE SESSION STATE
# ============================================================================

if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "assistant",
            "content": """👋 **Welcome to Zenline's Outdoor Retail Recommender!**

I'll help you discover emerging opportunities in outdoor retail, tailored to your company.

Let's start: **Do you have a company website URL to share?** (Or just type "skip" if you'd rather provide details another way)"""
        }
    ]

if "company_info" not in st.session_state:
    st.session_state.company_info = {
        "company_link": None,
        "market": None,
        "product_type": None,
        "company_docs": None,
        "notes": None
    }

if "conversation_stage" not in st.session_state:
    st.session_state.conversation_stage = "company_link"

# ============================================================================
# HEADER WITH LOGOS
# ============================================================================

col_logo, col_title = st.columns([1, 4])

with col_logo:
    zenline_logo_path = Path(__file__).parent.parent / "assets" / "zenline_logo.png"
    if zenline_logo_path.exists():
        st.image(str(zenline_logo_path), width=80)
    else:
        st.markdown("🏔️")

with col_title:
    st.title("Zenline Outdoor Recommender")
    st.caption("Discover emerging opportunities personalized to your company")

st.divider()

# ============================================================================
# CHAT DISPLAY
# ============================================================================

for message in st.session_state.messages:
    with st.chat_message(message["role"], avatar="🤖" if message["role"] == "assistant" else "👤"):
        st.markdown(message["content"])

# ============================================================================
# CHAT INPUT & LOGIC
# ============================================================================

def add_message(role: str, content: str):
    st.session_state.messages.append({"role": role, "content": content})


def _read_signals_csv():
    """Read signals.csv generated by Scout Agent."""
    from pathlib import Path
    import csv
    
    root = Path(__file__).resolve().parents[2]
    signals_path = root / "out" / "signals.csv"
    
    if not signals_path.exists():
        return []
    
    signals = []
    try:
        with open(signals_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Convert signal_score to float
                if "signal_score" in row:
                    try:
                        row["signal_score"] = float(row["signal_score"])
                    except (ValueError, TypeError):
                        row["signal_score"] = 0.5
                
                signals.append(row)
        
        # Sort by signal_score descending
        signals.sort(key=lambda x: x.get("signal_score", 0), reverse=True)
        return signals
    
    except Exception as e:
        print(f"Error reading signals.csv: {e}")
        return []


def _read_profile_json():
    """Read company_profile.json written by the pipeline (Agent 3 output)."""
    root = Path(__file__).resolve().parents[2]
    profile_path = root / "out" / "company_profile.json"
    if not profile_path.exists():
        return {"company_name": "Unknown"}
    try:
        with open(profile_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"Error reading company_profile.json: {e}")
        return {"company_name": "Unknown"}


user_input = st.chat_input("Type your response...")

if user_input:
    with st.chat_message("user", avatar="👤"):
        st.markdown(user_input)
    add_message("user", user_input)
    
    # ========================================================================
    # STAGE 1: Company Link
    # ========================================================================
    
    if st.session_state.conversation_stage == "company_link":
        user_lower = user_input.lower().strip()

        def _looks_like_url(text: str) -> bool:
            t = text.strip()
            if t.lower().startswith(("http://", "https://", "www.")):
                return True
            # Bare domain like "ochsnersport.ch" — a dotted token with a TLD,
            # no spaces.
            if " " not in t and "." in t:
                tld = t.rstrip("/").rsplit(".", 1)[-1]
                return tld.isalpha() and 2 <= len(tld) <= 24
            return False

        def _normalize_url(text: str) -> str:
            t = text.strip()
            if not t.lower().startswith(("http://", "https://")):
                t = "https://" + t
            return t

        if user_lower in ("skip", "no", "later") or user_lower.startswith(("skip", "no ", "later")):
            st.session_state.company_info["company_link"] = None
            st.session_state.conversation_stage = "market"
            
            response = """Got it! No problem. Let's gather info about your market focus instead.

**Which market(s) are you active in?** Please choose one:
- **CH** - Switzerland only
- **AT** - Austria only
- **DE** - Germany only
- **DACH** - All three (CH, AT, DE)
- **Other** - Different market"""
            
            with st.chat_message("assistant", avatar="🤖"):
                st.markdown(response)
            add_message("assistant", response)
        
        elif _looks_like_url(user_input):
            normalized = _normalize_url(user_input)
            st.session_state.company_info["company_link"] = normalized
            st.session_state.conversation_stage = "market"

            response = f"""✓ Got your website: **{normalized}**

Now, **which market(s) are you active in?** Please choose one:
- **CH** - Switzerland only
- **AT** - Austria only
- **DE** - Germany only
- **DACH** - All three (CH, AT, DE)
- **Other** - Different market"""
            
            with st.chat_message("assistant", avatar="🤖"):
                st.markdown(response)
            add_message("assistant", response)
        
        else:
            response = "Could you provide a URL (like https://www.yourcompany.ch) or type 'skip' to continue without one?"
            
            with st.chat_message("assistant", avatar="🤖"):
                st.markdown(response)
            add_message("assistant", response)
    
    # ========================================================================
    # STAGE 2: Market Selection
    # ========================================================================
    
    elif st.session_state.conversation_stage == "market":
        user_upper = user_input.upper().strip()
        
        if user_upper in ["CH", "AT", "DE", "DACH", "OTHER"]:
            st.session_state.company_info["market"] = user_upper
            st.session_state.conversation_stage = "product_type"
            
            response = f"""✓ Market set to: **{user_upper}**

Now, **what's your primary product focus?** 

(e.g., "ultralight hiking", "climbing", "winter sports", "sustainable gear", "family outdoor", etc.)"""
            
            with st.chat_message("assistant", avatar="🤖"):
                st.markdown(response)
            add_message("assistant", response)
        
        else:
            response = "Please choose one of the options: **CH**, **AT**, **DE**, **DACH**, or **Other**"
            
            with st.chat_message("assistant", avatar="🤖"):
                st.markdown(response)
            add_message("assistant", response)
    
    # ========================================================================
    # STAGE 3: Product Type (Free-form input)
    # ========================================================================
    
    elif st.session_state.conversation_stage == "product_type":
        product_type = user_input.strip()
        
        if product_type and product_type.lower() != "skip":
            st.session_state.company_info["product_type"] = product_type
            st.session_state.conversation_stage = "context"
            
            response = f"""✓ Product focus: **{product_type}**

**Any additional context about your company?** (Optional - e.g., store count, positioning, target margins)

Or type **"skip"** to proceed with analysis."""
            
            with st.chat_message("assistant", avatar="🤖"):
                st.markdown(response)
            add_message("assistant", response)
        
        else:
            response = "Please tell me your primary product focus (e.g., 'ultralight hiking', 'climbing', 'winter sports', 'family outdoor')."
            
            with st.chat_message("assistant", avatar="🤖"):
                st.markdown(response)
            add_message("assistant", response)
    
    # ========================================================================
    # STAGE 4: Additional Context
    # ========================================================================
    
    elif st.session_state.conversation_stage == "context":
        user_lower = user_input.lower().strip()
        
        if "skip" not in user_lower:
            st.session_state.company_info["notes"] = user_input
        
        st.session_state.conversation_stage = "analyzing"
        
        response = """🔍 **Analyzing your company...**

I'm extracting your company profile and sourcing emerging signals. This may take a moment."""
        
        with st.chat_message("assistant", avatar="🤖"):
            st.markdown(response)
        add_message("assistant", response)
    
    # ========================================================================
    # STAGE 5: Analyzing (Run Agents)
    # ========================================================================
    
    if st.session_state.conversation_stage == "analyzing":
        info = st.session_state.company_info
        market = info.get("market") or "DACH"
        if market == "OTHER":
            market = "DACH"
        product_type = info.get("product_type") or "outdoor products"
        company_link = info.get("company_link") or ""

        # Synthesize the Agent 2 query so parse_customer_query extracts a clean
        # product_focus + Scout seeds (matches the "… is looking for decision support on …" pattern).
        company_label = company_link or "A Swiss outdoor retailer"
        query = f"{company_label} is looking for decision support on {product_type}"

        with st.spinner("Running Scout + Profiler in parallel, then scoring with the Decision Agent…"):
            try:
                # Agent 2 orchestrator: parse → fan out Scout + Profiler (parallel) → join → score.
                result = run_pipeline(
                    query=query,
                    market=market,
                    company_link=company_link,
                    pdf_content=info.get("company_docs"),
                    user_notes=info.get("notes"),
                    max_steps=12,
                    write=True,
                    verbose=False,
                )
                st.session_state.recommendations = result
                st.session_state.pipeline_error = None
            except Exception as e:
                st.session_state.recommendations = {"recommendations": [], "error": str(e)}
                st.session_state.pipeline_error = str(e)

            # Profile + raw signals are written to disk by the pipeline — load them for the
            # Profile and Signals tabs.
            st.session_state.company_profile = _read_profile_json()
            st.session_state.signals = _read_signals_csv()

        st.session_state.conversation_stage = "results"

        company_name = st.session_state.company_profile.get("company_name", "Your Company")
        signal_count = len(st.session_state.signals)
        rec_count = len(st.session_state.recommendations.get("recommendations", []))

        if st.session_state.pipeline_error:
            results_msg = f"""⚠️ **Analysis ran into an error.**

```
{st.session_state.pipeline_error}
```

Check that `ANTHROPIC_API_KEY` is set and try **New Analysis** below."""
        else:
            results_msg = f"""✅ **Analysis complete for {company_name}!**

I sourced **{signal_count} emerging signals** in the **{market}** market and ranked them into **{rec_count} recommendations** tailored to your company.

📊 **Your results are ready** — see the tabs below:
- **Profile**: Key metrics, gaps, strategic direction
- **Signals**: Raw emerging signals (Agent 1)
- **Recommendations**: Ranked actions — what to launch, test, or monitor (Agent 2)"""

        with st.chat_message("assistant", avatar="🤖"):
            st.markdown(results_msg)
        add_message("assistant", results_msg)

# ============================================================================
# RESULTS DISPLAY
# ============================================================================

if st.session_state.conversation_stage == "results":
    st.divider()
    
    tab1, tab2, tab3 = st.tabs(["📋 Company Profile", "🔍 Emerging Signals", "🚀 Recommendations"])
    
    with tab1:
        if "company_profile" in st.session_state:
            profile = st.session_state.company_profile
            
            if "error" not in profile:
                col_a, col_b = st.columns(2)
                
                with col_a:
                    st.metric("Company", profile.get("company_name", "N/A"))
                    st.metric("Positioning", profile.get("positioning", "N/A"))
                    st.metric("Markets", ", ".join(profile.get("active_markets", [])) or "N/A")
                
                with col_b:
                    st.metric("Price Band", profile.get("target_price_band", "N/A"))
                    st.metric("Margin Target", profile.get("target_gross_margin", "N/A"))
                    st.metric("Innovation", profile.get("innovation_appetite", "N/A"))
                
                st.subheader("Current Gaps")
                st.write(profile.get("current_assortment_gaps", "None identified"))
                
                if profile.get("strategic_expansion_focus"):
                    st.subheader("📊 Strategic Direction")
                    st.success(f"""**Focus:** {profile.get('strategic_expansion_focus')}  
**Timeline:** {profile.get('strategic_timeline')}""")
                    
                    st.subheader("Strategic Gaps")
                    st.write(profile.get("strategic_assortment_gaps", "None"))
    
    with tab2:
        if "signals" in st.session_state and st.session_state.signals:
            signals = st.session_state.signals
            st.write(f"Found **{len(signals)}** signals:")
            
            for i, signal in enumerate(signals[:10], 1):
                with st.expander(
                    f"**{signal.get('signal_name', 'Unknown')}** • {signal.get('signal_type', 'N/A')} • Score: {signal.get('signal_score', 0):.2f}",
                    expanded=(i == 1)
                ):
                    col1, col2 = st.columns(2)
                    
                    with col1:
                        st.metric("Type", signal.get("signal_type", "N/A"))
                        st.metric("Market", signal.get("market", "N/A"))
                    
                    with col2:
                        st.metric("Price (CHF)", signal.get("price", "—"))
                        st.metric("Score", f"{signal.get('signal_score', 0):.2f}")
                    
                    st.write("**Notes:**")
                    st.caption(signal.get("notes", "No notes"))
    
    with tab3:
        rec_data = st.session_state.get("recommendations", {})
        recs = rec_data.get("recommendations", [])

        if rec_data.get("error"):
            st.error(f"Decision Agent error: {rec_data['error']}")
        elif not recs:
            st.info("No recommendations were produced. Try a different product focus or run a New Analysis.")
        else:
            _ACTION_STYLE = {
                "Launch": "🟢", "Test": "🟡", "Buy": "🟢",
                "Contact supplier/brand": "🟡", "Contact supplier": "🟡",
                "Monitor": "🔵", "Reposition existing assortment": "🟠", "Ignore": "⚪",
            }
            st.write(f"Ranked **{len(recs)}** opportunities for your company:")

            for rec in recs:
                action = rec.get("recommended_action", "Monitor")
                badge = _ACTION_STYLE.get(action.split(" — ")[0].strip(), "🔵")
                final = rec.get("scores", {}).get("final_score", 0)
                with st.expander(
                    f"**#{rec.get('rank', '?')} · {rec.get('opportunity', 'Opportunity')}** "
                    f"— {badge} {action.split(' — ')[0].strip()} · {final:.0f}/100",
                    expanded=(rec.get("rank") == 1),
                ):
                    c1, c2, c3 = st.columns(3)
                    with c1:
                        st.metric("Final score", f"{final:.0f}/100")
                        st.metric("Confidence", rec.get("confidence", "—"))
                    with c2:
                        st.metric("First seen", rec.get("first_observed_market", "—"))
                        st.metric("Coverage", rec.get("coverage_status", "—"))
                    with c3:
                        st.metric("Signals", rec.get("signal_count", 0))
                        st.metric("Sources", rec.get("source_count", 0))

                    st.markdown(f"**🎯 Recommended action:** {action}")
                    if rec.get("next_step"):
                        st.caption(rec["next_step"])

                    st.markdown("**Evidence**")
                    st.write(rec.get("evidence_summary", "—"))
                    for url in rec.get("evidence_urls", []):
                        st.markdown(f"- [{url}]({url})")

                    st.markdown("**Transferability**")
                    st.write(rec.get("transferability", "—"))

                    if rec.get("company_alignment_summary"):
                        st.markdown("**Fit to your company**")
                        st.write(rec["company_alignment_summary"])

                    risks = rec.get("risks", [])
                    if risks:
                        st.markdown("**Risks & missing evidence**")
                        for r in risks:
                            st.markdown(f"- {r}")

                    with st.popover("🔬 Score breakdown"):
                        scores = {k: v for k, v in rec.get("scores", {}).items()
                                  if isinstance(v, (int, float))}
                        st.json(scores)

            st.divider()
            csv_path = Path(__file__).resolve().parents[2] / "out" / "recommendations.csv"
            if csv_path.exists():
                with open(csv_path, "rb") as f:
                    st.download_button(
                        "⬇️ Download recommendations.csv (Zenline contract)",
                        data=f.read(),
                        file_name="recommendations.csv",
                        mime="text/csv",
                        use_container_width=True,
                    )
    
    st.divider()
    
    col1, col2 = st.columns(2)
    
    with col1:
        if st.button("🔄 New Analysis", use_container_width=True):
            for key in list(st.session_state.keys()):
                if key != "session_id":
                    del st.session_state[key]
            st.rerun()
    
    with col2:
        if st.button("📊 Export Results", use_container_width=True):
            st.info("Export feature coming soon")

st.divider()
st.markdown("""
<div style='text-align: center; color: #888; font-size: 11px;'>
    <strong>Zenline Outdoor Retail Recommender</strong> • Discover emerging opportunities<br>
    Powered by Claude AI + Scout Agent
</div>
""", unsafe_allow_html=True)